# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Alex\Documents\powerbox.ui',
# licensing of 'C:\Users\Alex\Documents\powerbox.ui' applies.
#
# Created: Sun Jun  2 22:14:57 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
import speech_recognition as sr


class Ui_Dialog(object):

    def append_log(self, message):
        self.textEdit.append(message)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(789, 530)
        Dialog.setMinimumSize(QtCore.QSize(789, 530))
        Dialog.setMaximumSize(QtCore.QSize(789, 530))
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        Dialog.setMouseTracking(False)
        Dialog.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/powerbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(1.0)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(211, 236, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background:transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(212, 212, 212)\n"
"}\n"
"QPushButton:pressed {\n"
"    background:rgb(195, 195, 195)\n"
"}\n"
"QTableWidget {\n"
"    border: none;\n"
"}\n"
"QScrollArea {\n"
"    background:white;\n"
"    color:white;\n"
"    background-color:white;\n"
"}")
        Dialog.setModal(True)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 500, 340))
        self.tabWidget.setObjectName("tabWidget")
        self.functions = QtWidgets.QWidget()
        self.functions.setObjectName("functions")
        self.tableWidget = QtWidgets.QTableWidget(self.functions)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 491, 318))
        self.tableWidget.setMinimumSize(QtCore.QSize(491, 311))
        self.tableWidget.setMaximumSize(QtCore.QSize(491, 16777215))
        self.tableWidget.setMouseTracking(True)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(11)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(68)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(68)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.functions, "")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.textEdit = QtWidgets.QTextEdit(self.log)
        self.textEdit.setGeometry(QtCore.QRect(10, 8, 451, 311))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    border: none;\n"
"}")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.log)
        self.pushButton.setGeometry(QtCore.QRect(462, 0, 32, 32))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/E:/Python/PowerBox/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.log, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.groupBox = QtWidgets.QGroupBox(self.settings)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 221, 61))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 22, 201, 22))
        for index, name in enumerate(sr.Microphone.list_microphone_names()):
                self.comboBox.addItem(name)
        self.comboBox.setObjectName("comboBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.settings)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 10, 221, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabWidget.addTab(self.settings, "")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 109, 109))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo/powerboxBright.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(171, 60, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(38, 96, 140);\n"
"}")
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 170, 60, 60))
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/E:/Python/PowerBox/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Время", None, -1))
        self.tableWidget.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Погода", None, -1))
        self.tableWidget.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("Dialog", "Открытие строки", None, -1))
        self.tableWidget.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("Dialog", "Выход из сеанса (Win + L)", None, -1))
        self.tableWidget.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("Dialog", "Завершение работы", None, -1))
        self.tableWidget.verticalHeaderItem(5).setText(QtWidgets.QApplication.translate("Dialog", "Отмена завершения работы", None, -1))
        self.tableWidget.verticalHeaderItem(6).setText(QtWidgets.QApplication.translate("Dialog", "Перезагрузка", None, -1))
        self.tableWidget.verticalHeaderItem(7).setText(QtWidgets.QApplication.translate("Dialog", "Отмена перезагрузки", None, -1))
        self.tableWidget.verticalHeaderItem(8).setText(QtWidgets.QApplication.translate("Dialog", "Математ. операции", None, -1))
        self.tableWidget.verticalHeaderItem(9).setText(QtWidgets.QApplication.translate("Dialog", "Написание текста", None, -1))
        self.tableWidget.verticalHeaderItem(10).setText(QtWidgets.QApplication.translate("Dialog", "Поиск в Интернете", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog", "Вкл.", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog", "Ключевые фразы", None, -1))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 1).setText(QtWidgets.QApplication.translate("Dialog", "сколько времени, текущее время, который час", None, -1))
        self.tableWidget.item(1, 1).setText(QtWidgets.QApplication.translate("Dialog", "какая погода, погода на сегодня", None, -1))
        self.tableWidget.item(2, 1).setText(QtWidgets.QApplication.translate("Dialog", "открыть строку, открыть поиск", None, -1))
        self.tableWidget.item(3, 1).setText(QtWidgets.QApplication.translate("Dialog", "заблокировать, выйти из сеанса", None, -1))
        self.tableWidget.item(4, 1).setText(QtWidgets.QApplication.translate("Dialog", "завершение работы, выключить компьютер", None, -1))
        self.tableWidget.item(5, 1).setText(QtWidgets.QApplication.translate("Dialog", "отмена завершения работы, отмена, не выключать компьютер", None, -1))
        self.tableWidget.item(6, 1).setText(QtWidgets.QApplication.translate("Dialog", "перезагрузить, перезагрузка компьютера", None, -1))
        self.tableWidget.item(7, 1).setText(QtWidgets.QApplication.translate("Dialog", "отмена, не выключать компьютер", None, -1))
        self.tableWidget.item(8, 1).setText(QtWidgets.QApplication.translate("Dialog", "сколько будет, посчитай", None, -1))
        self.tableWidget.item(9, 1).setText(QtWidgets.QApplication.translate("Dialog", "напечатай, напиши, напечатать, написать", None, -1))
        self.tableWidget.item(10, 1).setText(QtWidgets.QApplication.translate("Dialog", "искать в браузере, искать в интернете, ищи в браузере, поиск в интернете", None, -1))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.functions), QtWidgets.QApplication.translate("Dialog", "Функции", None, -1))
        self.textEdit.setHtml(QtWidgets.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:15pt; font-weight:600; font-style:normal;\">\n", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), QtWidgets.QApplication.translate("Dialog", "Лог", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Устройство записи", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Dialog", "Сочетание клавиш для вызова строки", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), QtWidgets.QApplication.translate("Dialog", "Настройки", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "PowerBox", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Everything you need.", None, -1))



